// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuthTokenPayload
 *
 * Payload for auth token responses (login, register, refresh).
 */
export type AuthTokenPayload = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token?: string;
    user: AppSchemasAuthSchemaUserOut;
};

/**
 * AuthTokenResponse
 *
 * Wrapped response for auth token endpoints.
 */
export type AuthTokenResponse = {
    status: ResponseStatus;
    /**
     * Message
     */
    message: string;
    data?: AuthTokenPayload | null;
    /**
     * Timestamp
     */
    timestamp?: string | null;
};

/**
 * Body_generate_splunk_config
 */
export type BodyGenerateSplunkConfig = {
    /**
     * Log File
     */
    log_file: Blob | File;
};

/**
 * Body_process_logs
 */
export type BodyProcessLogs = {
    /**
     * Log File
     */
    log_file: Blob | File;
};

/**
 * Body_process_media
 */
export type BodyProcessMedia = {
    /**
     * Input Url
     */
    input_url?: string;
    /**
     * Template Id
     */
    template_id: string;
    /**
     * Input File
     */
    input_file?: Blob | File | null;
    /**
     * Model
     */
    model?: string;
    /**
     * Media Type
     */
    media_type: string;
    /**
     * Enable Diarization
     */
    enable_diarization?: boolean;
    /**
     * Min Speakers
     */
    min_speakers?: number | null;
    /**
     * Max Speakers
     */
    max_speakers?: number | null;
};

/**
 * Body_process_web
 */
export type BodyProcessWeb = {
    /**
     * Input Url
     */
    input_url: string;
    /**
     * Template Id
     */
    template_id: string;
    /**
     * Model
     */
    model?: string | null;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Text
     */
    text: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
};

/**
 * CommentOut
 */
export type CommentOut = {
    /**
     * Text
     */
    text: string;
    /**
     * Id
     */
    id: number;
    /**
     * Content Id
     */
    content_id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Parent Id
     */
    parent_id: number | null;
    /**
     * Author Display Name
     */
    author_display_name: string;
};

/**
 * CommentUpdate
 */
export type CommentUpdate = {
    /**
     * Text
     */
    text: string;
};

/**
 * ContentCreate
 */
export type ContentCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Template Id
     */
    template_id?: number | null;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * ContentOut
 */
export type ContentOut = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Is Published
     */
    is_published?: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Template Id
     */
    template_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * View Count
     */
    view_count?: number;
    /**
     * Tags
     */
    tags: Array<string>;
    user: AppSchemasAuthSchemaUserOut;
    template?: TemplateOut | null;
};

/**
 * ContentTitleUpdate
 */
export type ContentTitleUpdate = {
    /**
     * Title
     */
    title: string;
};

/**
 * ContentUpdate
 */
export type ContentUpdate = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
};

/**
 * ConversationMessageOut
 */
export type ConversationMessageOut = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConversationRequest
 */
export type ConversationRequest = {
    /**
     * Message
     *
     * User message (max 5000 characters)
     */
    message: string;
    /**
     * Conversation Id
     *
     * Existing conversation to append to. If omitted, a new conversation is created.
     */
    conversation_id?: string | null;
    /**
     * Preserve Context
     *
     * When false, a new conversation branch is created even if conversation_id is provided.
     */
    preserve_context?: boolean;
    /**
     * Model
     *
     * Optional override for the generation model.
     */
    model?: string | null;
    /**
     * Branch From Id
     *
     * Create a branched conversation that references this parent conversation ID.
     */
    branch_from_id?: string | null;
    /**
     * Follow Up Type
     *
     * Optional identifier for which quick action or suggestion was selected.
     */
    follow_up_type?: string | null;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Content Id
     */
    content_id: number;
    /**
     * Updated Content
     */
    updated_content: string;
    /**
     * Model Used
     */
    model_used: string;
    /**
     * Change Summary
     */
    change_summary: Array<string>;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Suggestions
     */
    suggestions: Array<string>;
    /**
     * Messages
     */
    messages: Array<ConversationMessageOut>;
    /**
     * Branch Parent Id
     */
    branch_parent_id?: string | null;
    /**
     * Created New Conversation
     */
    created_new_conversation?: boolean;
};

/**
 * ConversationSummary
 */
export type ConversationSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Content Id
     */
    content_id: number;
    /**
     * Template Id
     */
    template_id?: number | null;
    /**
     * Template Used
     */
    template_used?: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Message Count
     */
    message_count: number;
};

/**
 * ConversationThreadOut
 */
export type ConversationThreadOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Content Id
     */
    content_id: number;
    /**
     * Template Id
     */
    template_id?: number | null;
    /**
     * Template Used
     */
    template_used?: string | null;
    /**
     * Model
     */
    model: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Message Count
     */
    message_count: number;
    /**
     * Messages
     */
    messages: Array<ConversationMessageOut>;
};

/**
 * CsrfTokenPayload
 *
 * Payload for CSRF token response.
 */
export type CsrfTokenPayload = {
    /**
     * Csrf Token
     */
    csrf_token: string;
};

/**
 * CsrfTokenResponse
 *
 * Wrapped response for CSRF token endpoint.
 */
export type CsrfTokenResponse = {
    status: ResponseStatus;
    /**
     * Message
     */
    message: string;
    data?: CsrfTokenPayload | null;
    /**
     * Timestamp
     */
    timestamp?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price: number;
};

/**
 * JobStatus
 */
export type JobStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled' | 'not_found';

/**
 * LogsProcessingResponse
 */
export type LogsProcessingResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * LogsProcessingStatusResponse
 */
export type LogsProcessingStatusResponse = {
    /**
     * Job Id
     */
    job_id: string;
    status: JobStatus;
    /**
     * Progress
     */
    progress?: number;
    stage?: ProcessingStage | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * MediaProcessingResponse
 */
export type MediaProcessingResponse = {
    /**
     * Job Id
     */
    job_id: string;
    status: MediaProcessingStatus;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * MediaProcessingStatus
 */
export type MediaProcessingStatus = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * MediaProcessingStatusResponse
 */
export type MediaProcessingStatusResponse = {
    /**
     * Job Id
     */
    job_id: string;
    status: JobStatus;
    /**
     * Progress
     */
    progress?: number;
    stage?: ProcessingStage | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Result
     */
    result?: string | {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * PaginatedResponse[ContentOut]
 */
export type PaginatedResponseContentOut = {
    /**
     * Items
     */
    items: Array<ContentOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Per Page
     */
    per_page: number;
};

/**
 * ProcessingStage
 *
 * Detailed processing stages for progress reporting.
 *
 * Each stage has a typical progress range:
 * - QUEUED: 0-5%
 * - DOWNLOADING: 5-20%
 * - CHUNKING: 20-30%
 * - TRANSCRIBING: 30-60%
 * - DIARIZING: 50-70% (overlaps with transcribing)
 * - GENERATING: 70-90%
 * - SAVING: 90-100%
 */
export type ProcessingStage = 'queued' | 'downloading' | 'chunking' | 'transcribing' | 'diarizing' | 'generating' | 'saving' | 'completed' | 'failed';

/**
 * ResponseModel[CommentOut]
 */
export type ResponseModelCommentOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: CommentOut | null;
};

/**
 * ResponseModel[ContentOut]
 */
export type ResponseModelContentOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: ContentOut | null;
};

/**
 * ResponseModel[ConversationResponse]
 */
export type ResponseModelConversationResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: ConversationResponse | null;
};

/**
 * ResponseModel[ConversationThreadOut]
 */
export type ResponseModelConversationThreadOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: ConversationThreadOut | null;
};

/**
 * ResponseModel[List[CommentOut]]
 */
export type ResponseModelListCommentOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<CommentOut> | null;
};

/**
 * ResponseModel[List[ConversationSummary]]
 */
export type ResponseModelListConversationSummary = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<ConversationSummary> | null;
};

/**
 * ResponseModel[List[TemplateOut]]
 */
export type ResponseModelListTemplateOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<TemplateOut> | null;
};

/**
 * ResponseModel[LogsProcessingResponse]
 */
export type ResponseModelLogsProcessingResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: LogsProcessingResponse | null;
};

/**
 * ResponseModel[LogsProcessingStatusResponse]
 */
export type ResponseModelLogsProcessingStatusResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: LogsProcessingStatusResponse | null;
};

/**
 * ResponseModel[NoneType]
 */
export type ResponseModelNoneType = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: null;
};

/**
 * ResponseModel[PaginatedResponse[ContentOut]]
 */
export type ResponseModelPaginatedResponseContentOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: PaginatedResponseContentOut | null;
};

/**
 * ResponseModel[TemplateOut]
 */
export type ResponseModelTemplateOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    data?: TemplateOut | null;
};

/**
 * ResponseModel[dict]
 */
export type ResponseModelDict = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ResponseModel[list]
 */
export type ResponseModelList = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<unknown> | null;
};

/**
 * ResponseModel[list[SubscriptionOut]]
 */
export type ResponseModelListSubscriptionOut = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<SubscriptionOut> | null;
};

/**
 * ResponseModel[list[dict]]
 */
export type ResponseModelListDict = {
    /**
     * Status
     */
    status: string;
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * ResponseStatus
 */
export type ResponseStatus = 'success' | 'error' | 'warning' | 'info';

/**
 * SubscriptionOut
 */
export type SubscriptionOut = {
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Plan
     */
    plan: string;
    /**
     * Status
     */
    status: string;
    /**
     * Stripe Customer Id
     */
    stripe_customer_id?: string | null;
    /**
     * Stripe Subscription Id
     */
    stripe_subscription_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    user?: UserBasicOut | null;
};

/**
 * TemplateCreate
 */
export type TemplateCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Template Content
     */
    template_content: string;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * User Id
     */
    user_id?: number | null;
};

/**
 * TemplateOut
 */
export type TemplateOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Template Content
     */
    template_content: string;
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Usage Count
     */
    usage_count?: number;
    user?: AppSchemasAuthSchemaUserOut | null;
};

/**
 * TemplateUpdate
 */
export type TemplateUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Template Content
     */
    template_content?: string | null;
};

/**
 * UserBasicOut
 */
export type UserBasicOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    role?: UserRole;
    /**
     * Password
     *
     * Password must be at least 8 characters long
     */
    password: string;
};

/**
 * UserCredits
 *
 * Summary of user's credit usage for the current billing period.
 */
export type UserCredits = {
    /**
     * Plan
     *
     * Current subscription plan
     */
    plan: string;
    /**
     * Limit
     *
     * Total credits available in this plan
     */
    limit: number;
    /**
     * Used
     *
     * Credits used this period
     */
    used: number;
    /**
     * Remaining
     *
     * Credits remaining this period
     */
    remaining: number;
    /**
     * Resets Monthly
     *
     * Whether credits reset monthly
     */
    resets_monthly?: boolean;
    /**
     * Is Admin
     *
     * Admin users have unlimited credits
     */
    is_admin?: boolean;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRole
 */
export type UserRole = 'USER' | 'ADMIN' | 'POWER' | 'MODERATOR' | 'GUEST';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * UserOut
 */
export type AppSchemasAuthSchemaUserOut = {
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    role?: UserRole;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Login
     */
    last_login?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Content Count
     */
    content_count?: number;
};

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Login
     */
    200: AuthTokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type LogoutResponses = {
    /**
     * Successfully Logged Out
     */
    200: unknown;
};

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Registration disabled
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * User registered successfully
     */
    201: AuthTokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Password Changed Successfully
     */
    200: unknown;
};

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh-token';
};

export type RefreshTokenErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type RefreshTokenResponses = {
    /**
     * Successful Response
     */
    200: AuthTokenResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type GetCsrfTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/csrf-token';
};

export type GetCsrfTokenErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetCsrfTokenResponses = {
    /**
     * CSRF Token
     */
    200: CsrfTokenResponse;
};

export type GetCsrfTokenResponse = GetCsrfTokenResponses[keyof GetCsrfTokenResponses];

export type SaveContentData = {
    body: ContentCreate;
    path?: never;
    query?: never;
    url: '/content/save-content';
};

export type SaveContentErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type SaveContentError = SaveContentErrors[keyof SaveContentErrors];

export type SaveContentResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelContentOut;
    /**
     * Content saved successfully
     */
    201: unknown;
};

export type SaveContentResponse = SaveContentResponses[keyof SaveContentResponses];

export type ListContentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
        /**
         * Template Id
         *
         * Filter by template ID
         */
        template_id?: number | null;
    };
    url: '/content/get-contents';
};

export type ListContentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ListContentsError = ListContentsErrors[keyof ListContentsErrors];

export type ListContentsResponses = {
    /**
     * Contents retrieved successfully
     */
    200: ResponseModelPaginatedResponseContentOut;
};

export type ListContentsResponse = ListContentsResponses[keyof ListContentsResponses];

export type GetContentData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/get-content/{content_id}';
};

export type GetContentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetContentError = GetContentErrors[keyof GetContentErrors];

export type GetContentResponses = {
    /**
     * Content retrieved successfully
     */
    200: ContentOut;
};

export type GetContentResponse = GetContentResponses[keyof GetContentResponses];

export type UpdateContentData = {
    body: ContentUpdate;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/update-content/{content_id}';
};

export type UpdateContentErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type UpdateContentError = UpdateContentErrors[keyof UpdateContentErrors];

export type UpdateContentResponses = {
    /**
     * Content updated successfully
     */
    200: ContentOut;
};

export type UpdateContentResponse = UpdateContentResponses[keyof UpdateContentResponses];

export type UpdateMultipleContentsData = {
    /**
     * Contents
     */
    body: Array<ContentUpdate>;
    path?: never;
    query?: never;
    url: '/content/update-multiple-contents';
};

export type UpdateMultipleContentsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type UpdateMultipleContentsError = UpdateMultipleContentsErrors[keyof UpdateMultipleContentsErrors];

export type UpdateMultipleContentsResponses = {
    /**
     * Response Update Multiple Contents
     *
     * Contents updated successfully
     */
    200: Array<ContentOut>;
};

export type UpdateMultipleContentsResponse = UpdateMultipleContentsResponses[keyof UpdateMultipleContentsResponses];

export type UpdateContentTitleData = {
    body: ContentTitleUpdate;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/update-title/{content_id}';
};

export type UpdateContentTitleErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type UpdateContentTitleError = UpdateContentTitleErrors[keyof UpdateContentTitleErrors];

export type UpdateContentTitleResponses = {
    /**
     * Content title updated successfully
     */
    200: ResponseModelContentOut;
};

export type UpdateContentTitleResponse = UpdateContentTitleResponses[keyof UpdateContentTitleResponses];

export type DeleteContentData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/delete-content/{content_id}';
};

export type DeleteContentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteContentError = DeleteContentErrors[keyof DeleteContentErrors];

export type DeleteContentResponses = {
    /**
     * Content deleted successfully
     */
    200: unknown;
};

export type ListCommentsData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/content/{content_id}/comments';
};

export type ListCommentsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Content not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ListCommentsError = ListCommentsErrors[keyof ListCommentsErrors];

export type ListCommentsResponses = {
    /**
     * Comments retrieved successfully
     */
    200: ResponseModelListCommentOut;
};

export type ListCommentsResponse = ListCommentsResponses[keyof ListCommentsResponses];

export type CreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/{content_id}/comments';
};

export type CreateCommentErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Content not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type CreateCommentError = CreateCommentErrors[keyof CreateCommentErrors];

export type CreateCommentResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelCommentOut;
    /**
     * Comment created successfully
     */
    201: unknown;
};

export type CreateCommentResponse = CreateCommentResponses[keyof CreateCommentResponses];

export type DeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/content/comments/{comment_id}';
};

export type DeleteCommentErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Comment not found or unauthorized
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteCommentError = DeleteCommentErrors[keyof DeleteCommentErrors];

export type DeleteCommentResponses = {
    /**
     * Comment deleted successfully
     */
    200: ResponseModelNoneType;
};

export type DeleteCommentResponse = DeleteCommentResponses[keyof DeleteCommentResponses];

export type UpdateCommentData = {
    body: CommentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: number;
    };
    query?: never;
    url: '/content/comments/{comment_id}';
};

export type UpdateCommentErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Comment not found or unauthorized
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type UpdateCommentError = UpdateCommentErrors[keyof UpdateCommentErrors];

export type UpdateCommentResponses = {
    /**
     * Comment updated successfully
     */
    200: ResponseModelCommentOut;
};

export type UpdateCommentResponse = UpdateCommentResponses[keyof UpdateCommentResponses];

export type ListContentConversationsData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/{content_id}/conversations';
};

export type ListContentConversationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Content not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ListContentConversationsError = ListContentConversationsErrors[keyof ListContentConversationsErrors];

export type ListContentConversationsResponses = {
    /**
     * Conversations retrieved successfully
     */
    200: ResponseModelListConversationSummary;
};

export type ListContentConversationsResponse = ListContentConversationsResponses[keyof ListContentConversationsResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: number;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/content/{content_id}/conversations/{conversation_id}';
};

export type DeleteConversationErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Conversation not found or unauthorized
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteConversationError = DeleteConversationErrors[keyof DeleteConversationErrors];

export type DeleteConversationResponses = {
    /**
     * Conversation deleted successfully
     */
    200: ResponseModelNoneType;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type GetConversationThreadData = {
    body?: never;
    path: {
        /**
         * Content Id
         */
        content_id: number;
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/content/{content_id}/conversations/{conversation_id}';
};

export type GetConversationThreadErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Conversation not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetConversationThreadError = GetConversationThreadErrors[keyof GetConversationThreadErrors];

export type GetConversationThreadResponses = {
    /**
     * Conversation retrieved successfully
     */
    200: ResponseModelConversationThreadOut;
};

export type GetConversationThreadResponse = GetConversationThreadResponses[keyof GetConversationThreadResponses];

export type ContinueConversationData = {
    body: ConversationRequest;
    path: {
        /**
         * Content Id
         */
        content_id: number;
    };
    query?: never;
    url: '/content/{content_id}/conversation';
};

export type ContinueConversationErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Content or conversation not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ContinueConversationError = ContinueConversationErrors[keyof ContinueConversationErrors];

export type ContinueConversationResponses = {
    /**
     * Conversation updated successfully
     */
    200: ResponseModelConversationResponse;
};

export type ContinueConversationResponse = ContinueConversationResponses[keyof ContinueConversationResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/template/get-templates';
};

export type ListTemplatesResponses = {
    /**
     * Templates retrieved successfully
     */
    200: ResponseModelListTemplateOut;
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type SaveTemplateData = {
    body: TemplateCreate;
    path?: never;
    query?: never;
    url: '/template/save-template';
};

export type SaveTemplateErrors = {
    /**
     * Invalid template content
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveTemplateError = SaveTemplateErrors[keyof SaveTemplateErrors];

export type SaveTemplateResponses = {
    /**
     * Template saved successfully
     */
    201: ResponseModelTemplateOut;
};

export type SaveTemplateResponse = SaveTemplateResponses[keyof SaveTemplateResponses];

export type GetTemplateData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/template/get-template/{template_id}';
};

export type GetTemplateErrors = {
    /**
     * Template not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTemplateError = GetTemplateErrors[keyof GetTemplateErrors];

export type GetTemplateResponses = {
    /**
     * Template retrieved successfully
     */
    200: ResponseModelTemplateOut;
};

export type GetTemplateResponse = GetTemplateResponses[keyof GetTemplateResponses];

export type UpdateTemplateData = {
    body: TemplateUpdate;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/template/update-template/{template_id}';
};

export type UpdateTemplateErrors = {
    /**
     * Invalid template content
     */
    400: unknown;
    /**
     * Template not found or unauthorized
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTemplateError = UpdateTemplateErrors[keyof UpdateTemplateErrors];

export type UpdateTemplateResponses = {
    /**
     * Template updated successfully
     */
    200: ResponseModelTemplateOut;
};

export type UpdateTemplateResponse = UpdateTemplateResponses[keyof UpdateTemplateResponses];

export type DeleteTemplateData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: number;
    };
    query?: never;
    url: '/template/delete-template/{template_id}';
};

export type DeleteTemplateErrors = {
    /**
     * Template not found or unauthorized
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateError = DeleteTemplateErrors[keyof DeleteTemplateErrors];

export type DeleteTemplateResponses = {
    /**
     * Template deleted successfully
     */
    200: ResponseModelNoneType;
};

export type DeleteTemplateResponse = DeleteTemplateResponses[keyof DeleteTemplateResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type GetUserProfileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUserProfileResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasAuthSchemaUserOut;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type ChangeDisplayNameData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/user/change-display-name';
};

export type ChangeDisplayNameErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ChangeDisplayNameError = ChangeDisplayNameErrors[keyof ChangeDisplayNameErrors];

export type ChangeDisplayNameResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasAuthSchemaUserOut;
};

export type ChangeDisplayNameResponse = ChangeDisplayNameResponses[keyof ChangeDisplayNameResponses];

export type ChangeEmailData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/user/change-email';
};

export type ChangeEmailErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ChangeEmailError = ChangeEmailErrors[keyof ChangeEmailErrors];

export type ChangeEmailResponses = {
    /**
     * Successful Response
     */
    200: AppSchemasAuthSchemaUserOut;
};

export type ChangeEmailResponse = ChangeEmailResponses[keyof ChangeEmailResponses];

export type GetUserCreditsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/credits';
};

export type GetUserCreditsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUserCreditsResponses = {
    /**
     * Successful Response
     */
    200: UserCredits;
};

export type GetUserCreditsResponse = GetUserCreditsResponses[keyof GetUserCreditsResponses];

export type GetUserUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/usage';
};

export type GetUserUsageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUserUsageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMediaConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/media/config';
};

export type GetMediaConfigErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMediaConfigResponses = {
    /**
     * Media file configuration
     */
    200: ResponseModelDict;
};

export type GetMediaConfigResponse = GetMediaConfigResponses[keyof GetMediaConfigResponses];

export type GetAvailableModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/media/models';
};

export type GetAvailableModelsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetAvailableModelsResponses = {
    /**
     * Available AI models for content generation
     */
    200: ResponseModelList;
};

export type GetAvailableModelsResponse = GetAvailableModelsResponses[keyof GetAvailableModelsResponses];

export type ProcessMediaData = {
    body: BodyProcessMedia;
    path?: never;
    query?: never;
    url: '/media/process-media';
};

export type ProcessMediaErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Template not found
     */
    404: unknown;
    /**
     * Payload Too Large
     */
    413: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ProcessMediaError = ProcessMediaErrors[keyof ProcessMediaErrors];

export type ProcessMediaResponses = {
    /**
     * Media processing job enqueued successfully
     */
    200: MediaProcessingResponse;
};

export type ProcessMediaResponse = ProcessMediaResponses[keyof ProcessMediaResponses];

export type GetMediaProcessingStatusData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/media/media-processing-status/{job_id}';
};

export type GetMediaProcessingStatusErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMediaProcessingStatusError = GetMediaProcessingStatusErrors[keyof GetMediaProcessingStatusErrors];

export type GetMediaProcessingStatusResponses = {
    /**
     * Media processing status retrieved successfully
     */
    200: MediaProcessingStatusResponse;
};

export type GetMediaProcessingStatusResponse = GetMediaProcessingStatusResponses[keyof GetMediaProcessingStatusResponses];

export type CreateItemData = {
    body: Item;
    path?: never;
    query?: never;
    url: '/items/';
};

export type CreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemError = CreateItemErrors[keyof CreateItemErrors];

export type CreateItemResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type ReadItemData = {
    body?: never;
    path: {
        /**
         * The ID of the item to get
         */
        item_id: number;
    };
    query?: {
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/items/{item_id}';
};

export type ReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemError = ReadItemErrors[keyof ReadItemErrors];

export type ReadItemResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type ReadUsersMeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessWebData = {
    body: BodyProcessWeb;
    path?: never;
    query?: never;
    url: '/web/process-web';
};

export type ProcessWebErrors = {
    /**
     * Invalid URL or missing parameters
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessWebError = ProcessWebErrors[keyof ProcessWebErrors];

export type ProcessWebResponses = {
    /**
     * Enqueued web scraping successfully
     */
    200: MediaProcessingStatusResponse;
};

export type ProcessWebResponse = ProcessWebResponses[keyof ProcessWebResponses];

export type GetWebProcessingStatusData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/web/web-processing-status/{job_id}';
};

export type GetWebProcessingStatusErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Job not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWebProcessingStatusError = GetWebProcessingStatusErrors[keyof GetWebProcessingStatusErrors];

export type GetWebProcessingStatusResponses = {
    /**
     * Successful Response
     */
    200: MediaProcessingStatusResponse;
};

export type GetWebProcessingStatusResponse = GetWebProcessingStatusResponses[keyof GetWebProcessingStatusResponses];

export type GetAdminUsageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/get-usage';
};

export type GetAdminUsageErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not authorized
     */
    403: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetAdminUsageResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListDict;
};

export type GetAdminUsageResponse = GetAdminUsageResponses[keyof GetAdminUsageResponses];

export type GetSubscriptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/get-subscriptions';
};

export type GetSubscriptionsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not authorized
     */
    403: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetSubscriptionsResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListSubscriptionOut;
};

export type GetSubscriptionsResponse = GetSubscriptionsResponses[keyof GetSubscriptionsResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessLogsData = {
    body: BodyProcessLogs;
    path?: never;
    query?: {
        /**
         * Anonymize
         *
         * Anonymize sensitive data before processing
         */
        anonymize?: boolean;
    };
    url: '/logs/process-logs';
};

export type ProcessLogsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type ProcessLogsError = ProcessLogsErrors[keyof ProcessLogsErrors];

export type ProcessLogsResponses = {
    /**
     * Log processing job enqueued successfully
     */
    200: ResponseModelLogsProcessingResponse;
};

export type ProcessLogsResponse = ProcessLogsResponses[keyof ProcessLogsResponses];

export type GetLogsProcessingStatusData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/logs/logs-processing-status/{job_id}';
};

export type GetLogsProcessingStatusErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Job not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetLogsProcessingStatusError = GetLogsProcessingStatusErrors[keyof GetLogsProcessingStatusErrors];

export type GetLogsProcessingStatusResponses = {
    /**
     * Log processing status retrieved successfully
     */
    200: ResponseModelLogsProcessingStatusResponse;
};

export type GetLogsProcessingStatusResponse = GetLogsProcessingStatusResponses[keyof GetLogsProcessingStatusResponses];

export type GenerateSplunkConfigData = {
    body: BodyGenerateSplunkConfig;
    path?: never;
    query?: {
        /**
         * Anonymize
         *
         * Anonymize sensitive data before processing
         */
        anonymize?: boolean;
    };
    url: '/logs/generate-splunk-config';
};

export type GenerateSplunkConfigErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GenerateSplunkConfigError = GenerateSplunkConfigErrors[keyof GenerateSplunkConfigErrors];

export type GenerateSplunkConfigResponses = {
    /**
     * Splunk config generation job enqueued successfully
     */
    200: ResponseModelLogsProcessingResponse;
};

export type GenerateSplunkConfigResponse = GenerateSplunkConfigResponses[keyof GenerateSplunkConfigResponses];

export type GetLogConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logs/config';
};

export type GetLogConfigErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Too Many Requests
     */
    429: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetLogConfigResponses = {
    /**
     * Log file configuration
     */
    200: ResponseModelDict;
};

export type GetLogConfigResponse = GetLogConfigResponses[keyof GetLogConfigResponses];
