"""add_template_id_to_contents

Revision ID: 5c41813cd26c
Revises: aaaa_add_usage_type_credits
Create Date: 2025-02-21 10:31:26.888652

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c41813cd26c"
down_revision: Union[str, None] = "aaaa_add_usage_type_credits"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contents", sa.Column("template_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contents", "template_id")
    # ### end Alembic commands ###
